### ISSUE TITLE
Non-AppImage Linux installation

### ISSUE THREAD

**Issue by l8doku** [Acly/krita-ai-tools#4]
If Krita is installed via a package manager it might be more convenient to have this plugin be added to the system Krita installation instead of an AppImage one.

I manually added the files from the linux release to my system dirs and it seems to work. I understand it might break things as it requires tinkering with the real root directory instead of the fake AppImage root.

The question/issue is, are there potential issues with this approach? For example, if I want to make an AUR package that places all the files into the user's /usr/lib and /usr/share, should it be that straightforward or is there something unexpected to look out for?

This might be out of the scope of this project, so feel free to close the issue.

**Comment by Acly** [comment]
Yes that should work. Installing is just copying the files, and uninstalling is removing them again. I also don't see any danger that something will be overwritten or breaks, because libraries are in the kritaplugins subfolder which only Krita uses. You shouldn't need to run ldconfig either.

The problem is more that there are many linux distros using various package managers and install paths and ways Krita is distributed aren't always exactly the same.

An AUR package which copies the binaries should work, although I'm not sure it's in the spirit of the thing (seems more intended to build from source?)

**Comment by l8doku** [comment]
I see, thank you! There are some AUR packages which install binaries, but yes, the default behavior is building from source.

It's all pretty new to me, so I'm not sure if I'll have time and motivation to make the package - now that I installed the plugin for myself I don't really need a new way of installing it. Still, I'll try to look into it.
